In [29]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df.APPLICATION_TYPE.value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df.CLASSIFICATION.value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop(['IS_SUCCESSFUL'], 1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

<ipython-input-10-df89e45518bf>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = application_df.drop(['IS_SUCCESSFUL'], 1).values

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [35]:
# Define the model - deep neural net
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=44))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 16)                720

 dense_17 (Dense)            (None, 32)                544

 dense_18 (Dense)            (None, 64)                2112

 dense_19 (Dense)            (None, 32)                2080

 dense_20 (Dense)            (None, 1)                 33

=================================================================
Total params: 5,489
Trainable params: 5,489
Non-trainable params: 0
_________________________________________________________________

In [36]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [37]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5795 - accuracy: 0.7142
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5552 - accuracy: 0.7275
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7301
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7313
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5481 - accuracy: 0.7324
Epoch 6/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5479 - accuracy: 0.7329
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7341
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7339
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7349
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7337
Epoch 11/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5446 - accuracy: 0.7343
Epoch 12/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5441 - accuracy: 0.7339
Epoch 13/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5436 - accuracy: 0.7345
Epoch 14/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5425 - accuracy: 0.7353
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5426 - accuracy: 0.7353
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7350
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7353
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7364
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7352
Epoch 20/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5412 - accuracy: 0.7368
Epoch 21/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5413 - accuracy: 0.7357
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7360
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7366
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7361
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7371
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7369
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5396 - accuracy: 0.7383
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7372
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7376
Epoch 31/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5392 - accuracy: 0.7369
Epoch 32/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7373
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5387 - accuracy: 0.7371
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7384
Epoch 35/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5382 - accuracy: 0.7377
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5384 - accuracy: 0.7379
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7378
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7381
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7379
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7380
Epoch 42/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5379 - accuracy: 0.7387
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7389
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7386
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7388
Epoch 46/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7389
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7391
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7378
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7386
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7389
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7381
Epoch 52/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5360 - accuracy: 0.7386
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7387
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7388
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7388
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7385
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7386
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7390
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7393
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7390
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7393
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7406
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7397
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5353 - accuracy: 0.7389
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7397
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7396
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7395
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.7393
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 71/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5344 - accuracy: 0.7397
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7394
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7395
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7392
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7395
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7395
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7397
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7401
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7406
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7402
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7403
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7402
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7399
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7402
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7401
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7394
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7401
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7403
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7406
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7405
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7403
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7403
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7404
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7405
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7400
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7407
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7405

In [39]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5651 - accuracy: 0.7300 - 372ms/epoch - 1ms/step
Loss: 0.5651370286941528, Accuracy: 0.7300291657447815

In [40]:
# Define the model - deep neural net
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=44))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_21 (Dense)            (None, 16)                720

 dense_22 (Dense)            (None, 32)                544

 dense_23 (Dense)            (None, 64)                2112

 dense_24 (Dense)            (None, 32)                2080

 dense_25 (Dense)            (None, 1)                 33

=================================================================
Total params: 5,489
Trainable params: 5,489
Non-trainable params: 0
_________________________________________________________________

In [41]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [42]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5788 - accuracy: 0.7164
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5563 - accuracy: 0.7277
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7278
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7300
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5491 - accuracy: 0.7296
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7313
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7324
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7320
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7328
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7341
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7335
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7336
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7349
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7342
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7347
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7358
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7345
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7365
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7346
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7362
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7368
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7367
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7365
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7357
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7368
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7362
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7370
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7369
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7375
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7364
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7375
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7373
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7381
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7370
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7375
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7378
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7386
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7383
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7366
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7392
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7385
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7379
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7390
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7380
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7382
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7383
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7384
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7388
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7391
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7389

In [43]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5581 - accuracy: 0.7296 - 532ms/epoch - 2ms/step
Loss: 0.5580922961235046, Accuracy: 0.7295626997947693

In [45]:
# Define the model - deep neural net
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=44))

# Second hidden layer
#nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Third hidden layer
#nn.add(tf.keras.layers.Dense(units=64, activation="relu"))

# Fourth hidden layer
#nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 16)                720

 dense_31 (Dense)            (None, 1)                 17

=================================================================
Total params: 737
Trainable params: 737
Non-trainable params: 0
_________________________________________________________________

In [46]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [49]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5449 - accuracy: 0.7329
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7330
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7338
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7332
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7335
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7333
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7322
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7323
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7327
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7336
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7332
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7333
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7328
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7343
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7332
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7330
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7329
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7333
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7334
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7333
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7336
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7329
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7339
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7328
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7323
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7329
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7338
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7337
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7334
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7341
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7333
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7341
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7330
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7338
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7333
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7336
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7343
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7338
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7331
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7339
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7343
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7331
Epoch 43/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5425 - accuracy: 0.7346
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7336
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7348
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7342
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7341
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7346
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7346
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7336
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7334
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7352
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7348
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7350
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7344
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7345
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7351
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7328
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7338
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7332
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7342
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7337
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7336
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7344
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7352
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7339
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7347
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7349
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7360
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7339
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7340
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7350
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7357
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7333
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7349
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7345
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7351
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7355
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7347
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7342
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7355
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7336
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7337
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7349
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7342
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7346
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7345
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7348
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7351
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7346
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7357
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7348
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7358
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7355
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7350
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7350
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7348
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7344
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7343

In [48]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5535 - accuracy: 0.7266 - 435ms/epoch - 2ms/step
Loss: 0.5534714460372925, Accuracy: 0.7266472578048706

In [50]:
# Define the model - deep neural net
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=44))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Third hidden layer
#nn.add(tf.keras.layers.Dense(units=64, activation="relu"))

# Fourth hidden layer
#nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_32 (Dense)            (None, 16)                720

 dense_33 (Dense)            (None, 32)                544

 dense_34 (Dense)            (None, 64)                2112

 dense_35 (Dense)            (None, 1)                 65

=================================================================
Total params: 3,441
Trainable params: 3,441
Non-trainable params: 0
_________________________________________________________________

In [51]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [52]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5798 - accuracy: 0.7132
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5577 - accuracy: 0.7285
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5525 - accuracy: 0.7306
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7310
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7313
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7325
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7318
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7327
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5470 - accuracy: 0.7327
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7321
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7336
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7335
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7332
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7321
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7325
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7335
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7336
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7336
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7340
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7341
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7340
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7346
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7348
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7337
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7358
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7346
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7356
Epoch 29/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7340
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7353
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7360
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7353
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7358
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7358
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5402 - accuracy: 0.7365
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7346
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7358
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7360
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7368
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7366
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7355
Epoch 42/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7368
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7359
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7358
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7358
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7356
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7369
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7364
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7365
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7372
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7364
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7374
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7373
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7379
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7365
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7375
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7374
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7378
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7380
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7376
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7382
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7390
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7381
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7384
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7385
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7386
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7382
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7387
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7383
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7387
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7389
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7376
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7395
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7387
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7386
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7383
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7387
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7372
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7388
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7387
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7391
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7397
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7395
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7390
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7390
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7399
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7396
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7389
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7390
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7389
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7385
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7392
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7394
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7404
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7399
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7393
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7385
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7397
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7400

In [53]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5604 - accuracy: 0.7277 - 515ms/epoch - 2ms/step
Loss: 0.5603705644607544, Accuracy: 0.7276967763900757

In [54]:
nn.save("AlphabetSoupCharity_Optimization.h5")